name: ROS2

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: osrf/ros:humble-desktop

    steps:
      - name: Create ROS 2 workspace
        run: mkdir -p ~/ros2_ws/src

      - name: Checkout repository into workspace
        uses: actions/checkout@v4
        with:
          path: ~/ros2_ws/src/${{ github.event.repository.name }}

      - name: Build with colcon
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ~/ros2_ws
          ls src/*
          colcon build --symlink-install
          ls .

