name: ROS2

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: osrf/ros:jazzy-desktop

    steps:
      - name: Checkout repository into workspace sources
        uses: actions/checkout@v4
        with:
          path: src/cpp_utils

      - name: Build with colcon
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --symlink-install
